# Generated by Django 4.2 on 2023-08-24 15:59

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=markdownx.models.MarkdownxField(verbose_name="内容"),
        ),
    ]
