# Generated by Django 4.2 on 2023-08-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_rename_is_draft_article_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="公開"),
        ),
    ]
