# Generated by Django 4.2 on 2023-08-30 05:17

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_rename_content_article_content_with_markdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content_with_markdown",
            field=markdownx.models.MarkdownxField(verbose_name="内容のマークダウン記述"),
        ),
    ]
