# Generated by Django 4.2 on 2023-08-30 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0006_alter_article_content_with_markdown"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "記事", "verbose_name_plural": "記事"},
        ),
    ]
