# Generated by Django 4.2 on 2023-09-16 11:53

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0007_alter_article_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bureau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="局名")),
                ("slug", models.SlugField(verbose_name="slug")),
                (
                    "content_with_markdown",
                    markdownx.models.MarkdownxField(verbose_name="局紹介文のマークダウン記述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最終更新日時"),
                ),
            ],
            options={
                "verbose_name": "局",
                "verbose_name_plural": "局",
            },
        ),
    ]
