# Generated by Django 4.2 on 2023-09-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0008_bureau"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="bureau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.bureau",
                verbose_name="記事局",
            ),
        ),
    ]
